//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tekkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjek
    {
        public int id { get; set; }
        public string subjek1 { get; set; }
    }
}
